[tool.poetry]
name = "bitwarden_event_logs"
version = "2.0.3"
description = "A Splunk app for reporting Bitwarden event logs."
authors = [
    "Bitwarden <hello@bitwarden.com>"
]
maintainers = [
    "Maciej Zieniuk <zieniuk.maciej@gmail.com>"
]
readme = "README.md"
keywords = ["splunk", "bitwarden"]

[tool.poetry.dependencies]
python = "3.7.16"
requests = "2.31.0"
splunk-sdk = "1.7.4"
splunktaucclib = "6.1.0"
python-dateutil = "2.9.0.post0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
python-dotenv = "0.21.1"
#flake8 = "*"
#black = "*"
#mypy = "*"
#isort = "*"
#pre-commit = "*"
#pre-commit-hooks = "*"
types-requests = "2.31.0.6"
#docformatter = {extras = ["tomli"], version = "^1.7.5"}
splunk-add-on-ucc-framework = "5.39.1"
splunk-appinspect = "3.4.0"

[tool.poetry.group.splunkslim]
optional = true

[tool.poetry.group.splunkslim.dependencies]
splunk-packaging-toolkit = "1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
