---
name: Build

on:
  push:
    branches-ignore:
      - 'l10n_master'
      - 'gh-pages'

jobs:
  build-artifacts:
    name: Build artifacts
    runs-on: windows-2022
    steps:
      - name: Checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Print environment
        run: |
          dotnet --info
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event: $GITHUB_EVENT"

      - name: Restore/Clean service
        run: |
          echo "Restore"
          dotnet restore
          echo "Clean"
          dotnet clean -c "Release"

      - name: Publish service
        shell: pwsh
        run: |
          ./build.ps1 -task app -os win
          ./build.ps1 -task app -os lin
          ./build.ps1 -task app -os mac

      - name: Upload artifacts (win-x64)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_win-x64
          path: build/app/win-x64
          if-no-files-found: error

      - name: Upload artifacts (win-x86)
        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
        with:
          name: bitwarden_event_logs_win-x86
          path: build/app/win-x86
          if-no-files-found: error
