---
name: Build

on:
  push:
    branches-ignore:
      - 'l10n_master'
      - 'gh-pages'

jobs:
  build-artifacts:
    name: Build artifacts
    runs-on: windows-2022
    steps:
      - name: Checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Print environment
        run: |
          dotnet --info
          echo "GitHub ref: $GITHUB_REF"
          echo "GitHub event: $GITHUB_EVENT"

      - name: Restore/Clean service
        run: |
          echo "Restore"
          dotnet restore
          echo "Clean"
          dotnet clean -c "Release"

      - name: Publish service (windows)
        shell: pwsh
        run: |
          ./build.ps1 -os win

      - name: Publish service (linux)
        shell: pwsh
        run: |
          ./build.ps1 -os lin

      - name: Publish service (macos)
        shell: pwsh
        run: |
          ./build.ps1 -os mac
